brew "cairo"
brew "pkg-config"
brew "fzf"
brew "zoxide"
brew "eza"
brew "bat"
brew "git-delta"
brew "hcloud"
brew "jq"
brew "uv"
brew "python@3.14"
brew "node@24"
brew "bun"
brew "go@1.26"
brew "dockutil"
brew "rust"
brew "helm"
brew "buf"
brew "gemini-cli"
brew "kubectl"
brew "gh"
brew "tilt"
brew "cloudflared"

# Casks that require /Applications for system integration
cask "displaylink"
cask "fastmail"
cask "zed"
