"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """$character"""
right_format = """$all"""

[package]
disabled = true

[git_metrics]
disabled = false

[gcloud]
disabled = true
