"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

#format = """$character"""
#right_format = """$all"""

[package]
disabled = true

[git_metrics]
disabled = false

[gcloud]
disabled = true

[character]
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
#format = " [$symbol$branch]($style) "
#symbol = "🍣 "
style = "yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "⚔️"
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇡${ahead_count} ⇣${behind_count} "
untracked = ""
stashed = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
style = "bg:red"
format = '[[( $all_status$ahead_behind)](bg:red)]($style) '

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = false