#/bin/bash

python utils/dock-icon-remove.py -r "/Applications/Launchpad.app"
python utils/dock-icon-remove.py -r "/Applications/Siri.app"
python utils/dock-icon-remove.py -r "/Applications/Safari.app"
python utils/dock-icon-remove.py -r "/Applications/Mail.app"
python utils/dock-icon-remove.py -r "/Applications/Contacts.app"
python utils/dock-icon-remove.py -r "/Applications/Calendar.app"
python utils/dock-icon-remove.py -r "/Applications/Reminders.app"
python utils/dock-icon-remove.py -r "/Applications/Maps.app"
python utils/dock-icon-remove.py -r "/Applications/Photos.app"
python utils/dock-icon-remove.py -r "/Applications/FaceTime.app"
python utils/dock-icon-remove.py -r "/Applications/iTunes.app"
python utils/dock-icon-remove.py -r "/Applications/App Store.app"
python utils/dock-icon-remove.py -r "/Applications/Podcasts.app"
python utils/dock-icon-remove.py -r "/Applications/TV.app"
python utils/dock-icon-remove.py -r "/Applications/Music.app"
python utils/dock-icon-remove.py -r "/Applications/Feedback Assistant.app"